### ISSUE TITLE
[Feat] 상세뷰 UI 구현

### ISSUE THREAD

**Issue by boogios** [DO-SOPT-APP4-MILLIE/Millie_iOS#14]
## 🌟ISSUE 
[Feat] 상세뷰 UI 구현

## 🌟TODO
- [ ] 부제 및 책 소개 뷰 구현
- [ ] 목차, 저자 소개, 출판사 서평 뷰 구현
- [ ] 바텀(담기, 바로 읽기) 고정 뷰구현
- [ ] 전체적인 코드 수정, ViewController를 View로 쪼개기
- [ ] 데이터 구조체 파일 추가
- [ ] 더미데이터 추가 및 적용
