### ISSUE TITLE
[Chore] 전반적인 기능 및 데이터 추가

### ISSUE THREAD

**Issue by ena-isme** [DO-SOPT-APP4-MILLIE/Millie_iOS#36]
## 🌟ISSUE 
[Chore] 전반적인 기능 및 데이터 추가

## 🌟TODO
- [x] 순위표로 넘어가는 버튼 구현
- [x] 마이페이지 바텀바 구현
- [x] 컬렉션뷰 더미데이터 넣기
